spring:
  application:
    name: "player1"
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    username: postgres
    password: gamedb
  jpa:
    generate-ddl: true

axon:
  axonserver:
    servers: localhost:8124
server:
  port: 8050